In [3]:
import pandas as pd

In [22]:
excerpts_official = pd.read_csv("sampled_excerpts_classification.csv", sep= ";")
excerpts = excerpts_official.copy()
excerpts

,ID,Channel Name,Plaintext,Channel Program,Frame,Secondary Frame,Tertariary Frame
0,bfba0757012516ce6d29bee725660dc9fa507993923f4a...,radio-2,pleiten samen voor zontaks. Want boerderijen w...,Flash Info 13:00,NaN,NaN,NaN
1,084728046cb62ee154329a1501e8973b8ff78ac1b21d38...,radio-1,hebben gekend. En in het licht van die grote o...,De Wereld Vand,Economy,NaN,NaN
2,460ffb08b4c91d8bb88a78871fd9c10feb13d8116c8afa...,canvas,dokwerkers. Ja moet jij met de fiets gaan werk...,De Afspraak,Policy,NaN,NaN
3,337110eaa733df7730dfadeb196b464a9fd7984b7c34fc...,radio-2,De Amerikaanse regering probeert de olieprijze...,Flash Info 08:00,Economy,NaN,NaN
4,6bd5336ca3af93a1a60d8dc81c5b4eb3127a6cab3c7513...,radio-2,Ga met Radio 1 naar de laatste dagen van Pompe...,Flash Info 13:00,Science / Expertise,NaN,NaN
...,...,...,...,...,...,...,...
345,256ab2918241bb78bf097c00f887c930a0a80847009061...,radio-2,Leer Sam kennen zoals nooit tevoren. Zijn gevo...,Flash Info 09:00,Economy,NaN,NaN
346,fd0934fb87d67113f77d91e7848468387e764c12037671...,play,Ja Jackie jij doet natuurlijk op rood kapken t...,De Tafel van Gert,NaN,NaN,NaN
347,5cf1a161f649d86ec744842a3a1d393da941e6647c78f4...,radio-2,Helicopters en drones. De Expo Flight. Tussen ...,Flash Info 17:00,Economy,NaN,NaN
348,96874f96c59f8cf4e00b4010444a812a34cc02496f8f1b...,vrt1,Bijen zijn in Vlaanderen gestorven deze winter...,VRT NWS Journaal 19:00,NaN,NaN,NaN
349,05e9dc7f2e15f15cbd481d32232fb84df4c9b62ca04033...,radio-1,Wat denk ik veel mensen wel opvalt is dat u pa...,De Ochtend,Policy,NaN,NaN

In [23]:
# Creating a new DataFrame with non-null values in the "Frame" column
excerpts.dropna(subset=["Frame"], inplace=True)
excerpts

,ID,Channel Name,Plaintext,Channel Program,Frame,Secondary Frame,Tertariary Frame
1,084728046cb62ee154329a1501e8973b8ff78ac1b21d38...,radio-1,hebben gekend. En in het licht van die grote o...,De Wereld Vand,Economy,NaN,NaN
2,460ffb08b4c91d8bb88a78871fd9c10feb13d8116c8afa...,canvas,dokwerkers. Ja moet jij met de fiets gaan werk...,De Afspraak,Policy,NaN,NaN
3,337110eaa733df7730dfadeb196b464a9fd7984b7c34fc...,radio-2,De Amerikaanse regering probeert de olieprijze...,Flash Info 08:00,Economy,NaN,NaN
4,6bd5336ca3af93a1a60d8dc81c5b4eb3127a6cab3c7513...,radio-2,Ga met Radio 1 naar de laatste dagen van Pompe...,Flash Info 13:00,Science / Expertise,NaN,NaN
9,cc7b797b81a47604eb1cbb9ba9cfe722e1bcad294f5d21...,radio-1,De gasprijzen pieken door de onrust in het Mid...,De Ochtend,Economy,NaN,NaN
...,...,...,...,...,...,...,...
338,8db00c0e849b6723e0fbc3356c9b3ea60407d72fd8ba21...,canvas,dat verlies aan concurrentiekracht. Maar als j...,De Afspraak,Policy,NaN,NaN
341,722bea4c0b08a7f26d8b61234f3968e907506a9981e3af...,canvas,Wel kan... Ja interessant. Zelfs waterdame kan...,De Afspraak,Economy,NaN,NaN
345,256ab2918241bb78bf097c00f887c930a0a80847009061...,radio-2,Leer Sam kennen zoals nooit tevoren. Zijn gevo...,Flash Info 09:00,Economy,NaN,NaN
347,5cf1a161f649d86ec744842a3a1d393da941e6647c78f4...,radio-2,Helicopters en drones. De Expo Flight. Tussen ...,Flash Info 17:00,Economy,NaN,NaN
349,05e9dc7f2e15f15cbd481d32232fb84df4c9b62ca04033...,radio-1,Wat denk ik veel mensen wel opvalt is dat u pa...,De Ochtend,Policy,NaN,NaN

In [24]:
# Counting the number of occurences of each frame in the "Frame"  and "Secondary Frame" column
frame_counts = excerpts["Frame"].value_counts()
frame_counts

Frame
Economy                74
Policy                 51
Science / Expertise    16
Name: count, dtype: int64

In [25]:
filtered_excerpts = pd.read_csv("filtered_excerpts.csv")
filtered_excerpts = filtered_excerpts[["ID", "Channel Name", "Plaintext", "Channel Program"]]
filtered_excerpts

,ID,Channel Name,Plaintext,Channel Program
0,b2bb7feb67f935b2cd48cc19980d5f55d68d1f414fd090...,play,aan ons land? En dan kwam ik bij dat thema. Eu...,De Tafel van Gert
1,ea6a0d0d8bceb4d412636b1b4e0e9e917e455cb2fb3681...,play,"Heerlijk lichte, knappere gewafeltjes omhult m...",De Tafel van Gert
2,b68678d8ed916b5d306f9c712ec00ff84ccb6c9519a68a...,vrt1,ongeveer 80 miljoen euro per toestel. Dus in t...,VRT NWS Journaal 22:30
3,df8a51ec2875b1fd7e4d8e5ebd14eff4021831f59325bf...,vtm,kernministers daarnaar gaat kijken of ons land...,VTM Daily News
4,a7b44638a33b1b5946098a7d02114a84b8cec1622beb11...,canvas,"voordeed. Namelijk, Iran was zo zwak dat eigen...",Terzake
...,...,...,...,...
3474,7995f224d6bb9dcc5f4e8e85c3526b734f47e50b48e262...,radio-1,Jouw energietransitie heeft een partner. Ik wa...,Het Journaal 08:00
3475,8d2fc504f66cbc0e820342f88921fda0b6e2990c33c2d8...,radio-1,remix. Het zou Zweeds kunnen zijn voor Vreewij...,Het Journaal 09:00
3476,8e14aee6c1cbbc4d400545ac072e0606a8b5c00e0211ba...,radio-1,Zeker. Er is heel veel grondwaarding en onbegr...,De Ochtend
3477,a32c0f99677ea4837582efe50159bd0a37fed5688f59eb...,qmusic,En er komt vandaag gewoon geen verandering in....,Flash Info 07:30
3478,0c63e580faa7831936a3593a423131f5eecd2532525aac...,qmusic,Zit jij op jouw terras te genieten van het goe...,Flash Info 08:30

In [26]:
# Deleting duplicate rows between excerpts and filtered_excerpts based on the "ID" column
filtered_excerpts = filtered_excerpts[~filtered_excerpts["ID"].isin(excerpts_official["ID"])]
filtered_excerpts

,ID,Channel Name,Plaintext,Channel Program
0,b2bb7feb67f935b2cd48cc19980d5f55d68d1f414fd090...,play,aan ons land? En dan kwam ik bij dat thema. Eu...,De Tafel van Gert
1,ea6a0d0d8bceb4d412636b1b4e0e9e917e455cb2fb3681...,play,"Heerlijk lichte, knappere gewafeltjes omhult m...",De Tafel van Gert
2,b68678d8ed916b5d306f9c712ec00ff84ccb6c9519a68a...,vrt1,ongeveer 80 miljoen euro per toestel. Dus in t...,VRT NWS Journaal 22:30
3,df8a51ec2875b1fd7e4d8e5ebd14eff4021831f59325bf...,vtm,kernministers daarnaar gaat kijken of ons land...,VTM Daily News
4,a7b44638a33b1b5946098a7d02114a84b8cec1622beb11...,canvas,"voordeed. Namelijk, Iran was zo zwak dat eigen...",Terzake
...,...,...,...,...
3473,0e41ad2af3efa595a5880a69487fbff150c1476b354bb8...,radio-2,"zal komen. Wel, de afgelopen dagen was dat wel...",Flash Info 13:00
3474,7995f224d6bb9dcc5f4e8e85c3526b734f47e50b48e262...,radio-1,Jouw energietransitie heeft een partner. Ik wa...,Het Journaal 08:00
3475,8d2fc504f66cbc0e820342f88921fda0b6e2990c33c2d8...,radio-1,remix. Het zou Zweeds kunnen zijn voor Vreewij...,Het Journaal 09:00
3476,8e14aee6c1cbbc4d400545ac072e0606a8b5c00e0211ba...,radio-1,Zeker. Er is heel veel grondwaarding en onbegr...,De Ochtend
3478,0c63e580faa7831936a3593a423131f5eecd2532525aac...,qmusic,Zit jij op jouw terras te genieten van het goe...,Flash Info 08:30

In [9]:
# Sampling 1000 random excerpts for analysis with no duplicates
sampled_excerpts_list = filtered_excerpts.sample(n=1000, random_state=42)
sampled_excerpts_list = sampled_excerpts_list[['ID','Channel Name', 'Plaintext', 'Channel Program']]
sampled_excerpts_list.to_csv("sampled_excerpts_newer.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'sampled_excerpts_newer.csv'

In [27]:
frame_analysis_df = pd.read_csv("sampled_excerpts_newer.csv", sep=";")
# Calculating count of each frame in the "Category"
frame_counts = frame_analysis_df["Frame"].value_counts()
frame_counts

Frame
Policy                 146
Economy                119
Science / Expertise     84
Name: count, dtype: int64

In [28]:
frame_analysis_df.dropna(subset=["Frame"], inplace=True)
frame_analysis_df

,ID,Channel Name,Plaintext,Channel Program,Frame
0,b50da4a35509efcc10fcae61ef6c9c5c31027c43b8d15f...,radio-1,"die al op de markt aanwezig zijn, zien hoe ze ...",De Ochtend,Economy
1,a8c84fa525d300c3a202ec67d1fa7c1a71387b7a39a9ba...,radio-2,...meest prioritaire lokale besturen geselecte...,Flash Info 07:00,Economy
5,6a3f3a2fa749e37eec27c4d7e09b718e80db193ad30d69...,radio-1,middelen daarvoor ter beschikking zouden kunne...,De Ochtend,Economy
6,7e074d1821031de2a7812852106663a7c7e07e4a80d05c...,radio-1,is en niet wanneer je zelf oké bent. En al rek...,De Ochtend,Science / Expertise
10,b4e45e8df61382bfeabaa1ce98308c6e1c3b1e8b30efb7...,vrt1,een van de grootste drijvende zonnepaneleninst...,VRT NWS Journaal 19:00,Economy
...,...,...,...,...,...
589,00e22034b8673e24e279341640b4ce6f6f10ac5c0a2662...,radio-2,"door die gas en olie vervoeren, maar sinds de ...",Flash Info 08:00,Policy
590,c608f8588ed77fe14d914420a71b92d02d8f845771b8c6...,radio-1,"Nu even een tekort is, gaan wij in de toekomst...",De Ochtend,Economy
595,8426c15395e8083762e7182f25fac0232953d874b55695...,play,"scoren, meestal zijn BNP Paribas en ING, dacht...",De Tafel van Gert,Economy
596,909e4c00fcfd28950abee1634a23fa0c88e3c5d73ad65d...,vtm,"Vier jaar geleden, de schok van de oorlog in O...",VTM Daily News,Economy
597,ab8f3c834a3a1d560b95ed20fb597062e9fb4ed5474830...,vrt1,nog aanwezig. Want Poetin en zijn gastheer Xi ...,VRT NWS Journaal 19:00,Economy

In [29]:
# Appending frame_analysis_df to excerpts DataFrame
excerpts = pd.concat([excerpts, frame_analysis_df], ignore_index=True)
excerpts

,ID,Channel Name,Plaintext,Channel Program,Frame,Secondary Frame,Tertariary Frame
0,084728046cb62ee154329a1501e8973b8ff78ac1b21d38...,radio-1,hebben gekend. En in het licht van die grote o...,De Wereld Vand,Economy,NaN,NaN
1,460ffb08b4c91d8bb88a78871fd9c10feb13d8116c8afa...,canvas,dokwerkers. Ja moet jij met de fiets gaan werk...,De Afspraak,Policy,NaN,NaN
2,337110eaa733df7730dfadeb196b464a9fd7984b7c34fc...,radio-2,De Amerikaanse regering probeert de olieprijze...,Flash Info 08:00,Economy,NaN,NaN
3,6bd5336ca3af93a1a60d8dc81c5b4eb3127a6cab3c7513...,radio-2,Ga met Radio 1 naar de laatste dagen van Pompe...,Flash Info 13:00,Science / Expertise,NaN,NaN
4,cc7b797b81a47604eb1cbb9ba9cfe722e1bcad294f5d21...,radio-1,De gasprijzen pieken door de onrust in het Mid...,De Ochtend,Economy,NaN,NaN
...,...,...,...,...,...,...,...
485,00e22034b8673e24e279341640b4ce6f6f10ac5c0a2662...,radio-2,"door die gas en olie vervoeren, maar sinds de ...",Flash Info 08:00,Policy,NaN,NaN
486,c608f8588ed77fe14d914420a71b92d02d8f845771b8c6...,radio-1,"Nu even een tekort is, gaan wij in de toekomst...",De Ochtend,Economy,NaN,NaN
487,8426c15395e8083762e7182f25fac0232953d874b55695...,play,"scoren, meestal zijn BNP Paribas en ING, dacht...",De Tafel van Gert,Economy,NaN,NaN
488,909e4c00fcfd28950abee1634a23fa0c88e3c5d73ad65d...,vtm,"Vier jaar geleden, de schok van de oorlog in O...",VTM Daily News,Economy,NaN,NaN
489,ab8f3c834a3a1d560b95ed20fb597062e9fb4ed5474830...,vrt1,nog aanwezig. Want Poetin en zijn gastheer Xi ...,VRT NWS Journaal 19:00,Economy,NaN,NaN

In [30]:
frame_counts = excerpts["Frame"].value_counts()
frame_counts

Frame
Policy                 197
Economy                193
Science / Expertise    100
Name: count, dtype: int64

In [31]:
!pip install sentence-transformers scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (4.1.0)
Requirement already satisfied: scikit-learn in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.5.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (4.46.2)
Requirement already satisfied: tqdm in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (2.5.1)
Requirement already satisfied: scipy in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (0.26.2)
Requirement already satisfied: Pillow in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (10.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sentence-transformers) (4.12.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: joblib>=1.2.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: filelock in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.9.0)
Requirement already satisfied: packaging>=20.9 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: networkx in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\viggo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [32]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2")

X = model.encode(excerpts["Plaintext"].tolist(), show_progress_bar=True)

y = excerpts["Frame"]

C:\Users\viggo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\viggo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\viggo\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Batches: 100%|██████████| 16/16 [01:11<00:00,  4.46s/it]

In [33]:
print(X.shape)

(490, 768)

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [35]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(
    max_iter=5000,
    class_weight="balanced"
)

clf.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=5000)

In [37]:
from sklearn.metrics import classification_report

predictions = clf.predict(X_test)

print(classification_report(y_test, predictions))

                     precision    recall  f1-score   support

            Economy       0.53      0.59      0.56        39
             Policy       0.43      0.41      0.42        39
Science / Expertise       0.61      0.55      0.58        20

           accuracy                           0.51        98
          macro avg       0.53      0.52      0.52        98
       weighted avg       0.51      0.51      0.51        98

In [12]:
# Deleting the top 200 rows fromt the sampled_excerpts_list DataFrame
sampled_excerpts_list = pd.read_csv("sampled_excerpts_newer.csv", sep=";")
sampled_excerpts_list = sampled_excerpts_list.iloc[200:]
sampled_excerpts_list

,ID,Channel Name,Plaintext,Channel Program,Unnamed: 4,Unnamed: 5
200,955e48d90596c84bdb69b9cb520f150c6e1f37542d169e...,vtm,Energie in op het juiste moment. Eneco. Je heb...,VTM Daily News,NaN,NaN
201,0113d04fb1476d06277e90f523c615feb3145d3f0e2a49...,radio-2,Omdat je nu bij Proximus 100 euro cashback ont...,Flash Info 16:00,NaN,NaN
202,f49547d086a36c089514e64824738e15b4c2bff7e0d9e3...,radio-1,Dat was in november vorig jaar geloof ik. Dat ...,De Ochtend,NaN,NaN
203,8a4eeff9a3e1d328725f00dee6aea9dfa275d661ab429f...,radio-1,Wat kan de Indiaanse regering doen? Het minist...,De Ochtend,NaN,NaN
204,7bb1497452f7d9da9292700e7835cba1f73642310e315c...,canvas,een van de drie kandidaten dit verhaal brengen...,De Afspraak,NaN,NaN
...,...,...,...,...,...,...
995,d7e7f16853d9b47dd2a7840de2c24bcb6d3a09e884345e...,radio-1,Hoeveel heb ik er al geeten misschien? En dan ...,De Ochtend,NaN,NaN
996,8d3deabaa7f06ba50fb597996cf2e5395ece621aedb16a...,vrt1,Het was ofwel een operatie ofwel in een rolsto...,VRT NWS Journaal 22:30,NaN,NaN
997,4df565827c167d3455cb1087e4e44a11fe8d321fa7b2b2...,radio-1,"Bij Hans? Ja, ja, het kan anders. Alles uit he...",Het Journaal 08:00,NaN,NaN
998,1dfe1788d7bb4e3dee1485e8e21c7196549f5372f8e05f...,play,"dat nu ook als chantage, wij lijden daar toch ...",De Tafel van Gert,NaN,NaN
999,b7ea9ef91a94378960bf3d52bc6e9db3a51640bf7ecbda...,radio-2,Radio 1 neemt je mee aan boord van de tentoons...,Flash Info 18:00,NaN,NaN

In [ ]:
import os
import json
import time
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

# ---------------------------------------------------------
# GLOBAL CONFIGURATION & POLICIES
# ---------------------------------------------------------
BATCH_SIZE = 100                    # 1,000 rows / 100 = 10 requests total (Safe under your 20 RPD cap)
TEMP_CHECKPOINT_FILE = "frame_analysis_checkpoint.csv"
FINAL_OUTPUT_FILE = "climate_frames_analysis.csv"

class ClimateCategory(str, Enum):
    SCIENCE = "Science / Expertise"
    POLICY = "Policy"
    ECONOMY = "Economy"

# ---------------------------------------------------------
# 1. STRUCTURAL RESPONSE BLUEPRINTS
# ---------------------------------------------------------
class CategorizationResultItem(BaseModel):
    ID: str = Field(description="The unique identifier string of the transcript.")
    category: Optional[ClimateCategory] = Field(
        default=None,
        description="The primary climate change category based on priority rules, or null if unrelated."
    )
    reason: str = Field(description="A 1-sentence analytical reason detailing which rules were applied.")

class FrameResponseSchema(BaseModel):
    results: List[CategorizationResultItem]

# ---------------------------------------------------------
# 2. HELPER STREAM ENGINE
# ---------------------------------------------------------
def chunk_dataframe(df: pd.DataFrame, size: int):
    for i in range(0, len(df), size):
        yield df.iloc[i : i + size]

# ---------------------------------------------------------
# 3. CORE CATEGORIZATION SYSTEM WITH AUTO-SAVE
# ---------------------------------------------------------
def categorize_climate_frames_with_recovery(df: pd.DataFrame):
    client = genai.Client(api_key="...")
    model_name = "gemini-2.5-flash"
    
    processed_ids = set()
    if os.path.exists(TEMP_CHECKPOINT_FILE):
        try:
            old_df = pd.read_csv(TEMP_CHECKPOINT_FILE)
            processed_ids = set(old_df['ID'].astype(str).tolist())
            print(f"Resuming from local file. Found {len(processed_ids)} already categorized records.")
        except Exception:
            print("Checkpoint empty or unreadable, starting fresh.")

    working_df = df[~df['ID'].isin(processed_ids)].copy()
    if working_df.empty:
        print("All excerpts have already been successfully analyzed!")
        return

    batches = list(chunk_dataframe(working_df, BATCH_SIZE))
    total_batches = len(batches)
    
    print(f"Initializing audit pipeline for {len(working_df)} rows across {total_batches} total requests...")
    
    system_instruction = (
        "You are an expert media content auditor specializing in framing analysis. "
        "Your task is to classify Flemish media log snippets into exactly ONE of the following categories, using a strict priority sequence:\n\n"
        "1. 'Science / Expertise': Contains scientific data, climate statistics, or insights shared by an expert. Policy advice backed up by statistics MUST be classified here.\n"
        "2. 'Policy': Focuses on climate-related rules, regulations, agreements, or strategies (including oil/gas policy) inside or outside Belgium.\n"
        "3. 'Economy': Explores economic impacts of climate change or financial/industrial shifts in related sectors (like oil and gas developments).\n\n"
        "STRICT PRIORITY RULE: If an excerpt exhibits indicators of multiple categories, you must prioritize 'Science / Expertise' first. "
        "If that is absent, prioritize 'Policy'. Only choose 'Economy' if it is completely isolated from the other two frames. "
        "If the excerpt does not explicitly or implicitly discuss climate change or related environmental sectors, do not assign a label (return null)."
    )

    for idx, batch_df in enumerate(batches, 1):
        print(f"Transmitting Batch {idx}/{total_batches} ({len(batch_df)} rows) to Gemini...")
        
        formatted_items = []
        for _, row in batch_df.iterrows():
            formatted_items.append(
                f"ID: {row['ID']}\nProgram: {row['Channel Program']} ({row['Channel Name']})\nExcerpt: {row['Plaintext']}\n---"
            )
            
        prompt = "Analyze these records and assign the single highest-priority category:\n\n" + "\n".join(formatted_items)
        batch_results_to_save = []
        
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    response_mime_type="application/json",
                    response_schema=FrameResponseSchema,
                    temperature=0.0,
                ),
            )
            
            clean_text = response.text.strip()
            if clean_text.startswith("```"):
                clean_text = clean_text.split("json")[-1].strip("` \n")
                
            parsed_json = json.loads(clean_text)
            batch_results_to_save = parsed_json.get("results", [])
            print(f"Batch {idx} read and classified cleanly!")
            
        except Exception as e:
            print(f"Batch {idx} hit a formatting/parsing anomaly: {e}")
            print(f"Splitting this specific batch into micro-chunks of 5 items to isolate the bad row...")
            
            micro_chunks = list(chunk_dataframe(batch_df, 5))
            for midx, micro_df in enumerate(micro_chunks, 1):
                micro_items = [f"ID: {row['ID']}\nExcerpt: {row['Plaintext']}\n---" for _, row in micro_df.iterrows()]
                micro_prompt = "Assign high-priority climate category:\n\n" + "\n".join(micro_items)
                try:
                    micro_response = client.models.generate_content(
                        model=model_name,
                        contents=micro_prompt,
                        config=types.GenerateContentConfig(
                            system_instruction=system_instruction,
                            response_mime_type="application/json",
                            response_schema=FrameResponseSchema,
                            temperature=0.0,
                        ),
                    )
                    m_text = micro_response.text.strip()
                    if m_text.startswith("```"):
                        m_text = m_text.split("json")[-1].strip("` \n")
                    batch_results_results = json.loads(m_text).get("results", [])
                    batch_results_to_save.extend(batch_results_results)
                except Exception:
                    for _, row in micro_df.iterrows():
                        batch_results_to_save.append({"ID": str(row['ID']), "category": None, "reason": "Failed parsing check"})
                time.sleep(1)

        # --- SAVE IMMEDIATELY TO HARD DRIVE ---
        if batch_results_to_save:
            current_checkpoint_df = pd.DataFrame(batch_results_to_save)
            if not os.path.exists(TEMP_CHECKPOINT_FILE):
                current_checkpoint_df.to_csv(TEMP_CHECKPOINT_FILE, index=False)
            else:
                current_checkpoint_df.to_csv(TEMP_CHECKPOINT_FILE, mode='a', header=False, index=False)
            print(f"Local progress saved! Checkpoint file appended with +{len(batch_results_to_save)} rows.")

        # --- MANDATORY TIME-OUT TO PREVENT QUOTA CEILINGS ---
        if idx < total_batches:
            print("Sleeping for 45 seconds to guarantee quota safety...")
            time.sleep(45)

# ---------------------------------------------------------
# 4. EXECUTE PIPELINE COHORT
# ---------------------------------------------------------
if __name__ == "__main__":
    # Target your specific dataframe name variable directly
    if 'sampled_excerpts_list' in locals() or 'sampled_excerpts_list' in globals():
        # Drop entries missing plain text and sample down exactly to your top 1000 items
        working_df = sampled_excerpts_list.dropna(subset=['Plaintext']).head(1000).copy()
        working_df['ID'] = working_df['ID'].astype(str)
        
        # Execute processing loop
        categorize_climate_frames_with_recovery(working_df)
        
        # --- COMPILE FINAL SEAMLESS FILE ---
        if os.path.exists(TEMP_CHECKPOINT_FILE):
            print("\Stitching frames back to target dataset...")
            results_df = pd.read_csv(TEMP_CHECKPOINT_FILE).drop_duplicates(subset=['ID'])
            results_df['ID'] = results_df['ID'].astype(str)
            
            final_dataset = pd.merge(working_df, results_df, on='ID', how='left')
            final_dataset.to_csv(FINAL_OUTPUT_FILE, index=False, encoding='utf-8')
            print(f"Mission Successful! Consolidated files saved to: '{FINAL_OUTPUT_FILE}'")
    else:
        print("Please ensure your 'sampled_excerpts_list' DataFrame is loaded into memory before running.")

<>:170: SyntaxWarning: invalid escape sequence '\S'
<>:170: SyntaxWarning: invalid escape sequence '\S'
C:\Users\viggo\AppData\Local\Temp\ipykernel_12656\1923295682.py:170: SyntaxWarning: invalid escape sequence '\S'
  print("\Stitching frames back to target dataset...")

Checkpoint empty or unreadable, starting fresh.
Initializing audit pipeline for 800 rows across 8 total requests...
Transmitting Batch 1/8 (100 rows) to Gemini...
Batch 1 read and classified cleanly!
Local progress saved! Checkpoint file appended with +100 rows.
Sleeping for 45 seconds to guarantee quota safety...
Transmitting Batch 2/8 (100 rows) to Gemini...
Batch 2 read and classified cleanly!
Local progress saved! Checkpoint file appended with +100 rows.
Sleeping for 45 seconds to guarantee quota safety...
Transmitting Batch 3/8 (100 rows) to Gemini...
Batch 3 read and classified cleanly!
Local progress saved! Checkpoint file appended with +100 rows.
Sleeping for 45 seconds to guarantee quota safety...
Transmitting Batch 4/8 (100 rows) to Gemini...
Batch 4 read and classified cleanly!
Local progress saved! Checkpoint file appended with +100 rows.
Sleeping for 45 seconds to guarantee quota safety...

C:\Users\viggo\AppData\Local\Temp\ipykernel_12656\1923295682.py:170: SyntaxWarning: invalid escape sequence '\S'
  print("\Stitching frames back to target dataset...")

KeyboardInterrupt:

In [ ]:
tv_excerpts = pd.read_csv("excerpts_tv_new.csv")
tv_excerpts

,ID,Channel Name,Channel Radio,Start,Plaintext,Theme,Created At,Keywords With Timestamp,Number Of Keywords,Srt,...,Number Of Attenuation Climatique Solutions No Hrfp,Number Of Adaptation Climatique Solutions No Hrfp,Number Of Ressources No Hrfp,Number Of Ressources Solutions No Hrfp,Number Of Biodiversite Concepts Generaux No Hrfp,Number Of Biodiversite Causes No Hrfp,Number Of Biodiversite Consequences No Hrfp,Number Of Biodiversite Solutions No Hrfp,Program Metadata ID,Country
0,005346829160b9347f958efb75434b0c51d43370276255...,play,False,"9 March, 2026, 20:56","Ja, huurlijk. Dan een verneinig. Dan wel. Maar...","[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1773086242...",0,"[{""cts_in_ms"": 1773086160000, ""duration_ms"": 5...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
1,c881ea2e3685131deef941f73127ca2e42668431665632...,play,False,"9 March, 2026, 21:14",mens is echt een heel groot verschil met een l...,"[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""wandelen"", ""timestamp"": 17730873...",0,"[{""cts_in_ms"": 1773087240170, ""duration_ms"": 2...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
2,9ee84b4b1428394754d9693d5568ffb1cfd50ec2635cb9...,play,False,"9 March, 2026, 20:46",Het is ook geloofwaardig. Dank u. De kinderen ...,"[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1773085657...",0,"[{""cts_in_ms"": 1773085566840, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
3,df498227fd02c041f22561a60569fb25447efccd9dd171...,play,False,"9 March, 2026, 20:14",die extreem rechtse vleuren van die Republikei...,"[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""meer"", ""timestamp"": 177308370609...",0,"[{""cts_in_ms"": 1773083640450, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
4,fc928e1930f5a843cf7c5ad5705c95f77540b603d8b895...,play,False,"9 March, 2026, 20:28","Maar toen kon ze eigenlijk weinig doen, behalv...","[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1773084583450...",0,"[{""cts_in_ms"": 1773084480920, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14147,9c1f14fa4a322f134014e0d53330ffd84018fa69da8182...,vrt1,False,"25 May, 2026, 22:46",Zette de voorzitter personeel van de Anderlech...,"[""ressources_indirectes"", ""attenuation_climati...",NaN,"[{""keyword"": ""bos"", ""timestamp"": 1779741989340...",0,"[{""cts_in_ms"": 1779741977980, ""duration_ms"": 5...",...,0,0,0,0,0,0,0,0,182c8876bbc403764c6544950610fa46439f9ea6aa49a0...,belgium
14148,17643c871a5ab886464d97b0a741196e1ed26e3bee4dc8...,vrt1,False,"25 May, 2026, 22:32",Ik heb nu vier dagen om even voetbal te verget...,"[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1779741158200...",0,"[{""cts_in_ms"": 1779741122020, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,182c8876bbc403764c6544950610fa46439f9ea6aa49a0...,belgium
14149,2e5e3e65dc0295556c5bf7f640d1b0085a15111792ca68...,vrt1,False,"25 May, 2026, 22:36",Ook morgen temperaturen die ver boven de 30 gr...,"[""changement_climatique_constat_indirectes"", ""...",NaN,"[{""keyword"": ""heetste dag"", ""timestamp"": 17797...",1,"[{""cts_in_ms"": 1779741360000, ""duration_ms"": 1...",...,0,0,0,0,0,0,0,0,182c8876bbc403764c6544950610fa46439f9ea6aa49a0...,belgium
14150,bcc2680f4ca6435207c7474a93d9e0147c4d0fe168f9e7...,vrt1,False,"25 May, 2026, 22:26",er financieel en fysiek toe in staat is. En da...,"[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""temperatuur"", ""timestamp"": 17797...",0,"[{""cts_in_ms"": 1779740760150, ""duration_ms"": 2...",...,0,0,0,0,0,0,0,0,182c8876bbc403764c6544950610fa46439f9ea6aa49a0...,belgium
14151,93bea755443f4716a461c2e6eb49ebbaa0dc44590e7f43...,vrt1,False,"25 May, 2026, 22:34",de cello 65 jaar lang bespeeld en het is recht...,"[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""zee"", ""timestamp"": 1779741303730...",0,"[{""cts_in_ms"": 1779741240040, ""duration_ms"": 1...",...,0,0,0,0,0,0,0,0,182c8876bbc403764c6544950610fa46439f9ea6aa49a0...,belgium

In [44]:
radio_excerpts = pd.read_csv("excerpts_radio_new.csv")
radio_excerpts

,ID,Channel Name,Channel Radio,Start,Plaintext,Theme,Created At,Keywords With Timestamp,Number Of Keywords,Srt,...,Number Of Attenuation Climatique Solutions No Hrfp,Number Of Adaptation Climatique Solutions No Hrfp,Number Of Ressources No Hrfp,Number Of Ressources Solutions No Hrfp,Number Of Biodiversite Concepts Generaux No Hrfp,Number Of Biodiversite Causes No Hrfp,Number Of Biodiversite Consequences No Hrfp,Number Of Biodiversite Solutions No Hrfp,Program Metadata ID,Country
0,f23ca70c44837ff8a28d81cc077d3ba36b4eed9ebbe787...,radio-2,True,"15 March, 2026, 12:42",lied voor geschreven. En Jan heeft onlangs nog...,"[""ressources_indirectes"", ""biodiversite_concep...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1773574970...",0,"[{""cts_in_ms"": 1773574920050, ""duration_ms"": 1...",...,0,0,0,0,0,0,0,0,45e8bbb60eed447cf7e5d716536c970b1d192551d14c61...,belgium
1,6bb9b0185315cf9a81a13059dea15698021a387ca24b6d...,radio-2,True,"15 March, 2026, 13:02",luide knallen gehoord. Waarna men is gaan kijk...,"[""changement_climatique_consequences_indirecte...",NaN,"[{""keyword"": ""kanker"", ""timestamp"": 1773576228...",0,"[{""cts_in_ms"": 1773576120270, ""duration_ms"": 6...",...,0,0,0,0,0,0,0,0,ef29111b292a25b43dc2ea51adea12ce20bdc2d1665e0b...,belgium
2,192542817ded8a657166770f5140d5336f68e41a44434c...,stu-bru,True,"9 March, 2026, 06:08",Ik kwam hier toe en er lag al een spoor aan sn...,"[""attenuation_climatique_solutions_indirectes""...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1773032927...",0,"[{""cts_in_ms"": 1773032880140, ""duration_ms"": 3...",...,0,0,0,0,0,0,0,0,e51f66a298a786009e17cb43ab327d43dc9c14a757b57f...,belgium
3,e551fb5eddd1771fdf83c6d81fdce6e41eb8e21e2c47b9...,stu-bru,True,"9 March, 2026, 06:00",Er wordt opnieuw gestaakt bij het spoor. Het i...,"[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1773032477710...",0,"[{""cts_in_ms"": 1773032476050, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,e51f66a298a786009e17cb43ab327d43dc9c14a757b57f...,belgium
4,d7684b8a49451df7de20228ef72ebceb3685d43f833eb3...,radio-2,True,"15 March, 2026, 16:10",Uit de 90's uiteraard. En over de 90's gesprok...,"[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1773587460710...",0,"[{""cts_in_ms"": 1773587450770, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,bdcd3cb128cfd29417f64a83bfe264ae559dae2b983bd6...,belgium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,a0e4b8f5260a178bdd6275375886b1c9f345b6964ad54c...,qmusic,True,"25 May, 2026, 18:36",Drive safe van Miles Midsa met Nyle Horren. Ik...,"[""ressources_indirectes"", ""biodiversite_concep...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1779726970...",0,"[{""cts_in_ms"": 1779726965460, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9ca4eaf0461beef18ae99f342419fd8a4a1885ed8cd624...,belgium
47377,37d6305cc2820018424675366d5047c849d4c5a78fbb5a...,qmusic,True,"25 May, 2026, 19:04",Mikel en onze landgenoot Dries de Bond. Vanavo...,"[""changement_climatique_causes_indirectes"", ""b...",NaN,"[{""keyword"": ""snelwegen"", ""timestamp"": 1779728...",0,"[{""cts_in_ms"": 1779728640000, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium
47378,b4419adaeb46f036754214a827c33c775e12d72fadfd9f...,qmusic,True,"25 May, 2026, 19:10","Oké, Gleesias en Channabal. Wat een dag zeg. R...","[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1779729114460...",0,"[{""cts_in_ms"": 1779729086000, ""duration_ms"": 2...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium
47379,1bcef12342742d6013640a9631ca2f359ed88a11a6c2a6...,qmusic,True,"25 May, 2026, 19:12",Het ziet er niet uit. Het is ook redelijk snel...,"[""ressources_indirectes"", ""biodiversite_concep...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1779729125...",0,"[{""cts_in_ms"": 1779729120530, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium
47380,87c5c9e210c07b41712017d0f8ae5566226383c61850a2...,qmusic,True,"25 May, 2026, 19:14",Ik vind het heel smakelijk nu dat je weg bent ...,"[""adaptation_climatique_solutions_indirectes"",...",NaN,"[{""keyword"": ""zwembad"", ""timestamp"": 177972934...",0,"[{""cts_in_ms"": 1779729303490, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium

In [45]:
# Appending the two dataframes together
combined_excerpts = pd.concat([tv_excerpts, radio_excerpts], ignore_index=True)
combined_excerpts

,ID,Channel Name,Channel Radio,Start,Plaintext,Theme,Created At,Keywords With Timestamp,Number Of Keywords,Srt,...,Number Of Attenuation Climatique Solutions No Hrfp,Number Of Adaptation Climatique Solutions No Hrfp,Number Of Ressources No Hrfp,Number Of Ressources Solutions No Hrfp,Number Of Biodiversite Concepts Generaux No Hrfp,Number Of Biodiversite Causes No Hrfp,Number Of Biodiversite Consequences No Hrfp,Number Of Biodiversite Solutions No Hrfp,Program Metadata ID,Country
0,005346829160b9347f958efb75434b0c51d43370276255...,play,False,"9 March, 2026, 20:56","Ja, huurlijk. Dan een verneinig. Dan wel. Maar...","[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1773086242...",0,"[{""cts_in_ms"": 1773086160000, ""duration_ms"": 5...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
1,c881ea2e3685131deef941f73127ca2e42668431665632...,play,False,"9 March, 2026, 21:14",mens is echt een heel groot verschil met een l...,"[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""wandelen"", ""timestamp"": 17730873...",0,"[{""cts_in_ms"": 1773087240170, ""duration_ms"": 2...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
2,9ee84b4b1428394754d9693d5568ffb1cfd50ec2635cb9...,play,False,"9 March, 2026, 20:46",Het is ook geloofwaardig. Dank u. De kinderen ...,"[""biodiversite_concepts_generaux_indirectes"", ...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1773085657...",0,"[{""cts_in_ms"": 1773085566840, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
3,df498227fd02c041f22561a60569fb25447efccd9dd171...,play,False,"9 March, 2026, 20:14",die extreem rechtse vleuren van die Republikei...,"[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""meer"", ""timestamp"": 177308370609...",0,"[{""cts_in_ms"": 1773083640450, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
4,fc928e1930f5a843cf7c5ad5705c95f77540b603d8b895...,play,False,"9 March, 2026, 20:28","Maar toen kon ze eigenlijk weinig doen, behalv...","[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1773084583450...",0,"[{""cts_in_ms"": 1773084480920, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,d63f1d3b25e104aff9fc0190ca8959d664c35ac665e596...,belgium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61528,a0e4b8f5260a178bdd6275375886b1c9f345b6964ad54c...,qmusic,True,"25 May, 2026, 18:36",Drive safe van Miles Midsa met Nyle Horren. Ik...,"[""ressources_indirectes"", ""biodiversite_concep...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1779726970...",0,"[{""cts_in_ms"": 1779726965460, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9ca4eaf0461beef18ae99f342419fd8a4a1885ed8cd624...,belgium
61529,37d6305cc2820018424675366d5047c849d4c5a78fbb5a...,qmusic,True,"25 May, 2026, 19:04",Mikel en onze landgenoot Dries de Bond. Vanavo...,"[""changement_climatique_causes_indirectes"", ""b...",NaN,"[{""keyword"": ""snelwegen"", ""timestamp"": 1779728...",0,"[{""cts_in_ms"": 1779728640000, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium
61530,b4419adaeb46f036754214a827c33c775e12d72fadfd9f...,qmusic,True,"25 May, 2026, 19:10","Oké, Gleesias en Channabal. Wat een dag zeg. R...","[""biodiversite_concepts_generaux_indirectes""]",NaN,"[{""keyword"": ""bij"", ""timestamp"": 1779729114460...",0,"[{""cts_in_ms"": 1779729086000, ""duration_ms"": 2...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium
61531,1bcef12342742d6013640a9631ca2f359ed88a11a6c2a6...,qmusic,True,"25 May, 2026, 19:12",Het ziet er niet uit. Het is ook redelijk snel...,"[""ressources_indirectes"", ""biodiversite_concep...",NaN,"[{""keyword"": ""mijnen"", ""timestamp"": 1779729125...",0,"[{""cts_in_ms"": 1779729120530, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium
61532,87c5c9e210c07b41712017d0f8ae5566226383c61850a2...,qmusic,True,"25 May, 2026, 19:14",Ik vind het heel smakelijk nu dat je weg bent ...,"[""adaptation_climatique_solutions_indirectes"",...",NaN,"[{""keyword"": ""zwembad"", ""timestamp"": 177972934...",0,"[{""cts_in_ms"": 1779729303490, ""duration_ms"": 4...",...,0,0,0,0,0,0,0,0,9c96dfb50301a2042afbb1ccc91f1a4ba9823aa1c6ba63...,belgium

In [46]:
combined_excerpts_needed = combined_excerpts[["ID", "Channel Name", "Start", "Plaintext", "Keywords With Timestamp","Channel Program", "Channel Title"]]
combined_excerpts_needed

,ID,Channel Name,Start,Plaintext,Keywords With Timestamp,Channel Program,Channel Title
0,005346829160b9347f958efb75434b0c51d43370276255...,play,"9 March, 2026, 20:56","Ja, huurlijk. Dan een verneinig. Dan wel. Maar...","[{""keyword"": ""mijnen"", ""timestamp"": 1773086242...",De Tafel van Gert,Play
1,c881ea2e3685131deef941f73127ca2e42668431665632...,play,"9 March, 2026, 21:14",mens is echt een heel groot verschil met een l...,"[{""keyword"": ""wandelen"", ""timestamp"": 17730873...",De Tafel van Gert,Play
2,9ee84b4b1428394754d9693d5568ffb1cfd50ec2635cb9...,play,"9 March, 2026, 20:46",Het is ook geloofwaardig. Dank u. De kinderen ...,"[{""keyword"": ""mijnen"", ""timestamp"": 1773085657...",De Tafel van Gert,Play
3,df498227fd02c041f22561a60569fb25447efccd9dd171...,play,"9 March, 2026, 20:14",die extreem rechtse vleuren van die Republikei...,"[{""keyword"": ""meer"", ""timestamp"": 177308370609...",De Tafel van Gert,Play
4,fc928e1930f5a843cf7c5ad5705c95f77540b603d8b895...,play,"9 March, 2026, 20:28","Maar toen kon ze eigenlijk weinig doen, behalv...","[{""keyword"": ""bij"", ""timestamp"": 1773084583450...",De Tafel van Gert,Play
...,...,...,...,...,...,...,...
61528,a0e4b8f5260a178bdd6275375886b1c9f345b6964ad54c...,qmusic,"25 May, 2026, 18:36",Drive safe van Miles Midsa met Nyle Horren. Ik...,"[{""keyword"": ""mijnen"", ""timestamp"": 1779726970...",Flash Info 18:30,QMUSIC
61529,37d6305cc2820018424675366d5047c849d4c5a78fbb5a...,qmusic,"25 May, 2026, 19:04",Mikel en onze landgenoot Dries de Bond. Vanavo...,"[{""keyword"": ""snelwegen"", ""timestamp"": 1779728...",Flash Info 19:00,QMUSIC
61530,b4419adaeb46f036754214a827c33c775e12d72fadfd9f...,qmusic,"25 May, 2026, 19:10","Oké, Gleesias en Channabal. Wat een dag zeg. R...","[{""keyword"": ""bij"", ""timestamp"": 1779729114460...",Flash Info 19:00,QMUSIC
61531,1bcef12342742d6013640a9631ca2f359ed88a11a6c2a6...,qmusic,"25 May, 2026, 19:12",Het ziet er niet uit. Het is ook redelijk snel...,"[{""keyword"": ""mijnen"", ""timestamp"": 1779729125...",Flash Info 19:00,QMUSIC
61532,87c5c9e210c07b41712017d0f8ae5566226383c61850a2...,qmusic,"25 May, 2026, 19:14",Ik vind het heel smakelijk nu dat je weg bent ...,"[{""keyword"": ""zwembad"", ""timestamp"": 177972934...",Flash Info 19:00,QMUSIC

In [38]:
thematics_keywords = pd.read_csv("thematics_keywords_new.csv")
thematics_keywords

,Channel Title,Country,Week,Category,High Risk Of False Positive,Is Solution,Is Consequence,Is Cause,Is General Concepts,Is Statement,...,Agriculture,Transport,Batiments,Energie,Industrie,Eau,Ecosysteme,Economie Ressources,Count,Sum Duration Minutes
0,RADIO 1,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,80,2 030
1,RADIO 1,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,60,2 030
2,Canvas,belgium,"2 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,48,375
3,Canvas,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,48,375
4,RADIO 1,belgium,"16 March, 2026",General,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,40,2 030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7094,STU BRU,belgium,"11 May, 2026",Transversal,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470
7095,STU BRU,belgium,"11 May, 2026",Transversal,True,False,True,False,False,False,...,False,False,False,False,False,False,True,False,1,1 470
7096,STU BRU,belgium,"11 May, 2026",Transversal,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470
7097,STU BRU,belgium,"11 May, 2026",Transversal,True,True,False,False,False,False,...,False,True,False,True,False,False,False,False,1,1 470
7098,STU BRU,belgium,"11 May, 2026",Transversal,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470

In [ ]:
# If High Risk Of False Positive = True, delete from thematics_keywords DataFrame
thematics_keywords = thematics_keywords[thematics_keywords["High Risk Of False Positive"] != True]
thematics_keywords

,Channel Title,Country,Week,Category,High Risk Of False Positive,Is Solution,Is Consequence,Is Cause,Is General Concepts,Is Statement,...,Agriculture,Transport,Batiments,Energie,Industrie,Eau,Ecosysteme,Economie Ressources,Count,Sum Duration Minutes
0,RADIO 1,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,80,2 030
1,RADIO 1,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,60,2 030
2,Canvas,belgium,"2 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,48,375
3,Canvas,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,48,375
4,RADIO 1,belgium,"16 March, 2026",General,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,40,2 030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7084,STU BRU,belgium,"4 May, 2026",Transversal,NaN,False,False,False,True,False,...,False,False,False,False,False,True,False,False,1,1 470
7087,STU BRU,belgium,"11 May, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,1,1 470
7088,STU BRU,belgium,"11 May, 2026",Transversal,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,1,1 470
7089,STU BRU,belgium,"11 May, 2026",Transversal,False,True,False,False,False,False,...,False,True,False,True,False,False,False,False,1,1 470
7090,STU BRU,belgium,"11 May, 2026",Transversal,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470

In [41]:
# Getting a list of all unique keywords in the Keyword column of thematics_keywords DataFrame
all_unique_keywords = set()
for keywords in thematics_keywords["Keyword"]:
    if pd.notna(keywords):
        all_unique_keywords.update([kw.strip() for kw in keywords.split(",")])
print(f"Total unique keywords (all): {len(all_unique_keywords)}")

Total unique keywords (all): 268

In [47]:
# Filtering to make sure all unique keywords (non-HRFP) are selected as target keywords, after which all excerpts containing them are saved in filtered_df
import json

# Looping over all unique keywords and checking if they are present in the dataset
target_keywords = all_unique_keywords

def contains_target_keyword(cell):
    try:
        data = json.loads(cell)

        return any(
            item.get("keyword", "").lower() in target_keywords
            for item in data
        )

    except Exception:
        return False


filtered_df_final = combined_excerpts_needed[combined_excerpts_needed["Keywords With Timestamp"].apply(contains_target_keyword)]
filtered_df_final

,ID,Channel Name,Start,Plaintext,Keywords With Timestamp,Channel Program,Channel Title
9,b2bb7feb67f935b2cd48cc19980d5f55d68d1f414fd090...,play,"9 March, 2026, 20:02",aan ons land? En dan kwam ik bij dat thema. Eu...,"[{""keyword"": ""mijnen"", ""timestamp"": 1773083016...",De Tafel van Gert,Play
11,a0bbd585362466cf13ea6d9de34bb5ca73a37a92a792ac...,play,"16 March, 2026, 19:58",Bon appétit. Wat als je gele tinten in het ech...,"[{""keyword"": ""gerecycled plastic"", ""timestamp""...",De Tafel van Gert,Play
18,78a8caec54e565bff31af86c2eafd4f4c33965533a2dbb...,play,"9 March, 2026, 20:52",Shit. Shit. Want de mooiste sport ter wereld v...,"[{""keyword"": ""minder beton"", ""timestamp"": 1773...",De Tafel van Gert,Play
25,d969c28e2ae8c42f59d229c3c3079e29ac961efa73d13d...,play,"24 March, 2026, 20:26",Ademvrij met Qviva. 100 % natuurlijk en doeltr...,"[{""keyword"": ""park"", ""timestamp"": 177438045644...",De Tafel van Gert,Play
27,1e65516fc565c1141e5562ccd4fc5d5a8f3ff7d3a1e2c7...,vrt1,"9 March, 2026, 13:22",Cerkelen en komt weer naast de Brugge op de tw...,"[{""keyword"": ""zee"", ""timestamp"": 1773058990420...",VRT NWS Journaal 13:00,VRT 1
...,...,...,...,...,...,...,...
61511,237fe4db47c023b7ae126e360ff6617d1ecb773b136de9...,qmusic,"25 May, 2026, 16:44","Ja, wij doen lasercleaning. Wij gaan eigenlijk...","[{""keyword"": ""mijnen"", ""timestamp"": 1779720254...",Flash Info 16:30,QMUSIC
61518,d36a3bdcac0d25e38f5c204ae10b51a77fa2c285efedd0...,qmusic,"25 May, 2026, 17:34",zoal wat verder op de weekaart kijken? Zit er ...,"[{""keyword"": ""snelwegen"", ""timestamp"": 1779723...",Flash Info 17:30,QMUSIC
61523,27f4ae7a4955a33b56149e9ab53fea6ae5b7fc83092c3e...,qmusic,"25 May, 2026, 19:02",De autoverzekering is een product aangeboden d...,"[{""keyword"": ""beperking"", ""timestamp"": 1779728...",Flash Info 19:00,QMUSIC
61526,4a10082939f15793a69a32cc03f0f4f758eed85ab71e25...,qmusic,"25 May, 2026, 18:32",Ik ben zeer benieuwd. Ook daar wat een verslag...,"[{""keyword"": ""zee"", ""timestamp"": 1779726728980...",Flash Info 18:30,QMUSIC
61527,2ce1ff79fb1214a57af910013a55a57f8c5f328939d189...,qmusic,"25 May, 2026, 18:44",Two night is the night. Two night worden 20 gr...,"[{""keyword"": ""mijnen"", ""timestamp"": 1779727518...",Flash Info 18:30,QMUSIC

### Logistic Regression

In [48]:
X_full = model.encode(
    filtered_df_final["Plaintext"].tolist(),
    show_progress_bar=True
)

Batches: 100%|██████████| 396/396 [23:59<00:00,  3.63s/it]

In [ ]:
filtered_df_final["Predicted_Frame_Logistic"] = clf.predict(X_full)

C:\Users\viggo\AppData\Local\Temp\ipykernel_12656\3998260750.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_final["Predicted_Frame"] = clf.predict(X_full)

In [52]:
probs = clf.predict_proba(X_full)
print(probs[0])

[0.26426396 0.6098654  0.12587064]

In [ ]:
import plotly.express as px

frame_counts = (
    filtered_df_final["Predicted_Frame_Logistic"]
    .value_counts()
    .reset_index()
)

frame_counts.columns = ["Frame", "Count"]

fig = px.bar(
    frame_counts,
    x="Frame",
    y="Count",
    title="Distribution of Predicted Climate Frames"
)

fig.show()

In [ ]:
channel_frames = (
    filtered_df_final.groupby(
        ["Channel Name", "Predicted_Frame_Logistic"]
    )
    .size()
    .reset_index(name="Count")
)

fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Count",
    color="Predicted_Frame_Logistic",
    title="Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [ ]:
# Percentage of each frame within each channel
channel_totals = (
    filtered_df_final.groupby("Channel Name")
    .size()
    .reset_index(name="Total")
)
channel_frames = channel_frames.merge(channel_totals, on="Channel Name")
channel_frames["Percentage"] = (channel_frames["Count"] / channel_frames["Total"]) * 100

# Creating a percentage-based bar chart
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Percentage",
    color="Predicted_Frame_Logistic",
    title="Percentage Distribution of Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [ ]:
channel_frames_program = (
    filtered_df_final.groupby(
        ["Channel Program", "Predicted_Frame_Logistic"]
    )
    .size()
    .reset_index(name="Count")
)

fig = px.bar(
    channel_frames_program,
    x="Channel Program",
    y="Count",
    color="Predicted_Frame_Logistic",
    title="Predicted Climate Frames by Channel Program",
    barmode="group"
)

fig.show()

In [ ]:
import json

# Keywords to search for
target_keywords = {"klimaat", "milieu", "natuur", "duurzaamheid", "ecologie", "landbouw", "pesticide", "brandstof", "ecologisch", "vervuild", "vergroenen", "droogte", "groene energie", "pfas", "zonnepanelen", "co2", "hernieuwbare energie", "extreme hitte", "hittegolf", "vervuilen", "natuurgebied", "gas", "fossiele brandstoffen", "klimaatverandering", "aardgas", "steenkool", "aardolie", "windenergie", "windmolen", "green deal"}

def contains_target_keyword(cell):
    try:
        data = json.loads(cell)

        return any(
            item.get("keyword", "").lower() in target_keywords
            for item in data
        )

    except Exception:
        return False

# Example:
# df["keywords_column"] contains the JSON strings

filtered_df = combined_excerpts_needed[combined_excerpts_needed["Keywords With Timestamp"].apply(contains_target_keyword)]

filtered_df

,ID,Channel Name,Start,Plaintext,Keywords With Timestamp,Channel Program,Channel Title
9,b2bb7feb67f935b2cd48cc19980d5f55d68d1f414fd090...,play,"9 March, 2026, 20:02",aan ons land? En dan kwam ik bij dat thema. Eu...,"[{""keyword"": ""mijnen"", ""timestamp"": 1773083016...",De Tafel van Gert,Play
22,ea6a0d0d8bceb4d412636b1b4e0e9e917e455cb2fb3681...,play,"16 March, 2026, 20:22","Heerlijk lichte, knappere gewafeltjes omhult m...","[{""keyword"": ""gas"", ""timestamp"": 1773689033910...",De Tafel van Gert,Play
37,b68678d8ed916b5d306f9c712ec00ff84ccb6c9519a68a...,vrt1,"9 March, 2026, 22:50",ongeveer 80 miljoen euro per toestel. Dus in t...,"[{""keyword"": ""productie"", ""timestamp"": 1773093...",VRT NWS Journaal 22:30,VRT 1
38,df8a51ec2875b1fd7e4d8e5ebd14eff4021831f59325bf...,vtm,"19 March, 2026, 19:06",kernministers daarnaar gaat kijken of ons land...,"[{""keyword"": ""gas"", ""timestamp"": 1773943622780...",VTM Daily News,VTM
49,a7b44638a33b1b5946098a7d02114a84b8cec1622beb11...,canvas,"10 March, 2026, 20:08","voordeed. Namelijk, Iran was zo zwak dat eigen...","[{""keyword"": ""gas"", ""timestamp"": 1773169784070...",Terzake,Canvas
...,...,...,...,...,...,...,...
61415,7995f224d6bb9dcc5f4e8e85c3526b734f47e50b48e262...,radio-1,"25 May, 2026, 08:02",Jouw energietransitie heeft een partner. Ik wa...,"[{""keyword"": ""gas"", ""timestamp"": 1779689014610...",Het Journaal 08:00,RADIO 1
61447,8d2fc504f66cbc0e820342f88921fda0b6e2990c33c2d8...,radio-1,"25 May, 2026, 09:02",remix. Het zou Zweeds kunnen zijn voor Vreewij...,"[{""keyword"": ""suv"", ""timestamp"": 1779692619810...",Het Journaal 09:00,RADIO 1
61454,8e14aee6c1cbbc4d400545ac072e0606a8b5c00e0211ba...,radio-1,"25 May, 2026, 07:56",Zeker. Er is heel veel grondwaarding en onbegr...,"[{""keyword"": ""voeding"", ""timestamp"": 177968864...",De Ochtend,RADIO 1
61493,a32c0f99677ea4837582efe50159bd0a37fed5688f59eb...,qmusic,"25 May, 2026, 07:36",En er komt vandaag gewoon geen verandering in....,"[{""keyword"": ""landbouw"", ""timestamp"": 17796874...",Flash Info 07:30,QMUSIC
61502,0c63e580faa7831936a3593a423131f5eecd2532525aac...,qmusic,"25 May, 2026, 08:32",Zit jij op jouw terras te genieten van het goe...,"[{""keyword"": ""mijnen"", ""timestamp"": 1779690722...",Flash Info 08:30,QMUSIC

In [19]:
filtered_df.to_csv("filtered_excerpts.csv", index=False)

In [40]:
# Sampling 350 random excerpts for analysis with no duplicates
filtered_df = pd.read_csv("filtered_excerpts.csv")
sampled_excerpts = filtered_df.sample(n=350, random_state=42)
sampled_excerpts = sampled_excerpts[['ID','Channel Name', 'Plaintext', 'Channel Program']]
sampled_excerpts.to_csv("sampled_excerpts_new.csv", index=False)

In [66]:
frame_analysis_df = pd.read_csv("sampled_excerpts_newer.csv", sep=";")
frame_analysis_df = frame_analysis_df[0:600]
frame_analysis_df

,ID,Channel Name,Plaintext,Channel Program,Frame
0,b50da4a35509efcc10fcae61ef6c9c5c31027c43b8d15f...,radio-1,"die al op de markt aanwezig zijn, zien hoe ze ...",De Ochtend,Economy
1,a8c84fa525d300c3a202ec67d1fa7c1a71387b7a39a9ba...,radio-2,...meest prioritaire lokale besturen geselecte...,Flash Info 07:00,Economy
2,fe129a691a78c262cf5999b99d30eb7b1c708e2133550d...,vrt1,"Wat is dat, jongen? Het is tijd dat ik go down...",VRT NWS Journaal 22:30,NaN
3,f98f11608d1215bc6ae7ccc4223cb7bd8e0f7ec2b7386f...,radio-1,Zo kan ik blijven doorgaan tot de dag van vand...,De Wereld Vand,NaN
4,05e92cea49f79f97b157423f79cc7253966ea6e5e3818a...,qmusic,Ik dat ik weet waarvoor elk knopje dient. Inde...,Flash Info 07:30,NaN
...,...,...,...,...,...
595,8426c15395e8083762e7182f25fac0232953d874b55695...,play,"scoren, meestal zijn BNP Paribas en ING, dacht...",De Tafel van Gert,Economy
596,909e4c00fcfd28950abee1634a23fa0c88e3c5d73ad65d...,vtm,"Vier jaar geleden, de schok van de oorlog in O...",VTM Daily News,Economy
597,ab8f3c834a3a1d560b95ed20fb597062e9fb4ed5474830...,vrt1,nog aanwezig. Want Poetin en zijn gastheer Xi ...,VRT NWS Journaal 19:00,Economy
598,b341e0060e64ba22fc07953f5c24f9942788fb72243140...,play,Ben je moe? Wist je dat ProMagnor je kan helpe...,De Tafel van Gert,NaN
599,1acb2b4f8b4de2c4618f184b0bcb14739aa05ac100b6fa...,radio-1,aan het omkopen is. Of zelfs aan het intimider...,De Ochtend,NaN

In [68]:
excerpts_official = pd.read_csv("sampled_excerpts_classification.csv", sep= ";")
excerpts_official_empty_frame = excerpts_official[excerpts_official["Frame"].isna()]
excerpts_official_empty_frame

,ID,Channel Name,Plaintext,Channel Program,Frame,Secondary Frame,Tertariary Frame
0,bfba0757012516ce6d29bee725660dc9fa507993923f4a...,radio-2,pleiten samen voor zontaks. Want boerderijen w...,Flash Info 13:00,NaN,NaN,NaN
5,0eb1d9019c5c58fc96336939d4a355bf28ba0808fe2899...,play,Ik was een kenner eigenlijk. was eigenlijk een...,De Tafel van Gert,NaN,NaN,NaN
6,513650bd086964b6faa0a8551fb86032fdf8259e7d46d7...,vtm,Dus sommig geld gevonden. De klan zou zich dan...,VTM Daily News,NaN,NaN,NaN
7,c4b38f956a29db23feff3dbbc5237cff0165c80c85b48d...,stu-bru,euro plus BTW. Dat geldt voor de Europese Unie...,Flash Info 09:00,NaN,NaN,NaN
8,84ab0355aa4ac546397cbd2227f6402272f9debd03bc24...,radio-1,Daar bent u wakker van geworden Lerita Mitsuko...,De Ochtend,NaN,NaN,NaN
...,...,...,...,...,...,...,...
342,6b5fbf8e6aa27b26ca72148cb11096ea8ba8e36bfc9599...,radio-2,de Kroo. Niet alleen voor dit opruimwerk maar ...,Flash Info 18:00,NaN,NaN,NaN
343,db8b03f9d76d4da8ec5cf2cd636f3cbc43a173c85e8492...,radio-2,Ik ben Filip Geubels en ik ben angstcoach gewo...,Flash Info 14:00,NaN,NaN,NaN
344,0e534324b6a8c755500b75849ce8a53409fb67881b10a2...,canvas,Mijn vlakke land? Oké Jacques maar klein detai...,Terzake,NaN,NaN,NaN
346,fd0934fb87d67113f77d91e7848468387e764c12037671...,play,Ja Jackie jij doet natuurlijk op rood kapken t...,De Tafel van Gert,NaN,NaN,NaN
348,96874f96c59f8cf4e00b4010444a812a34cc02496f8f1b...,vrt1,Bijen zijn in Vlaanderen gestorven deze winter...,VRT NWS Journaal 19:00,NaN,NaN,NaN

In [72]:
# Appending excerpts_official_empty_frame to excerpts DataFrame
excerpts_with_na = pd.concat([excerpts_official_empty_frame, excerpts], ignore_index=True)
excerpts_with_na

,ID,Channel Name,Plaintext,Channel Program,Frame,Secondary Frame,Tertariary Frame
0,bfba0757012516ce6d29bee725660dc9fa507993923f4a...,radio-2,pleiten samen voor zontaks. Want boerderijen w...,Flash Info 13:00,NaN,NaN,NaN
1,0eb1d9019c5c58fc96336939d4a355bf28ba0808fe2899...,play,Ik was een kenner eigenlijk. was eigenlijk een...,De Tafel van Gert,NaN,NaN,NaN
2,513650bd086964b6faa0a8551fb86032fdf8259e7d46d7...,vtm,Dus sommig geld gevonden. De klan zou zich dan...,VTM Daily News,NaN,NaN,NaN
3,c4b38f956a29db23feff3dbbc5237cff0165c80c85b48d...,stu-bru,euro plus BTW. Dat geldt voor de Europese Unie...,Flash Info 09:00,NaN,NaN,NaN
4,84ab0355aa4ac546397cbd2227f6402272f9debd03bc24...,radio-1,Daar bent u wakker van geworden Lerita Mitsuko...,De Ochtend,NaN,NaN,NaN
...,...,...,...,...,...,...,...
694,00e22034b8673e24e279341640b4ce6f6f10ac5c0a2662...,radio-2,"door die gas en olie vervoeren, maar sinds de ...",Flash Info 08:00,Policy,NaN,NaN
695,c608f8588ed77fe14d914420a71b92d02d8f845771b8c6...,radio-1,"Nu even een tekort is, gaan wij in de toekomst...",De Ochtend,Economy,NaN,NaN
696,8426c15395e8083762e7182f25fac0232953d874b55695...,play,"scoren, meestal zijn BNP Paribas en ING, dacht...",De Tafel van Gert,Economy,NaN,NaN
697,909e4c00fcfd28950abee1634a23fa0c88e3c5d73ad65d...,vtm,"Vier jaar geleden, de schok van de oorlog in O...",VTM Daily News,Economy,NaN,NaN
698,ab8f3c834a3a1d560b95ed20fb597062e9fb4ed5474830...,vrt1,nog aanwezig. Want Poetin en zijn gastheer Xi ...,VRT NWS Journaal 19:00,Economy,NaN,NaN

In [73]:
# Changing missing values in the "Frame" column to "Unrelated"
excerpts_with_na["Frame"] = excerpts_with_na["Frame"].fillna("Unrelated")
excerpts_with_na

,ID,Channel Name,Plaintext,Channel Program,Frame,Secondary Frame,Tertariary Frame
0,bfba0757012516ce6d29bee725660dc9fa507993923f4a...,radio-2,pleiten samen voor zontaks. Want boerderijen w...,Flash Info 13:00,Unrelated,NaN,NaN
1,0eb1d9019c5c58fc96336939d4a355bf28ba0808fe2899...,play,Ik was een kenner eigenlijk. was eigenlijk een...,De Tafel van Gert,Unrelated,NaN,NaN
2,513650bd086964b6faa0a8551fb86032fdf8259e7d46d7...,vtm,Dus sommig geld gevonden. De klan zou zich dan...,VTM Daily News,Unrelated,NaN,NaN
3,c4b38f956a29db23feff3dbbc5237cff0165c80c85b48d...,stu-bru,euro plus BTW. Dat geldt voor de Europese Unie...,Flash Info 09:00,Unrelated,NaN,NaN
4,84ab0355aa4ac546397cbd2227f6402272f9debd03bc24...,radio-1,Daar bent u wakker van geworden Lerita Mitsuko...,De Ochtend,Unrelated,NaN,NaN
...,...,...,...,...,...,...,...
694,00e22034b8673e24e279341640b4ce6f6f10ac5c0a2662...,radio-2,"door die gas en olie vervoeren, maar sinds de ...",Flash Info 08:00,Policy,NaN,NaN
695,c608f8588ed77fe14d914420a71b92d02d8f845771b8c6...,radio-1,"Nu even een tekort is, gaan wij in de toekomst...",De Ochtend,Economy,NaN,NaN
696,8426c15395e8083762e7182f25fac0232953d874b55695...,play,"scoren, meestal zijn BNP Paribas en ING, dacht...",De Tafel van Gert,Economy,NaN,NaN
697,909e4c00fcfd28950abee1634a23fa0c88e3c5d73ad65d...,vtm,"Vier jaar geleden, de schok van de oorlog in O...",VTM Daily News,Economy,NaN,NaN
698,ab8f3c834a3a1d560b95ed20fb597062e9fb4ed5474830...,vrt1,nog aanwezig. Want Poetin en zijn gastheer Xi ...,VRT NWS Journaal 19:00,Economy,NaN,NaN

In [74]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2")

X = model.encode(excerpts_with_na["Plaintext"].tolist(), show_progress_bar=True)

y = excerpts_with_na["Frame"]

Batches: 100%|██████████| 22/22 [01:44<00:00,  4.75s/it]

In [75]:
print(X.shape)

(699, 768)

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [77]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(
    max_iter=5000,
    class_weight="balanced"
)

clf.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=5000)

In [78]:
from sklearn.metrics import classification_report

predictions = clf.predict(X_test)

print(classification_report(y_test, predictions))

                     precision    recall  f1-score   support

            Economy       0.43      0.49      0.46        39
             Policy       0.41      0.33      0.37        39
Science / Expertise       0.48      0.55      0.51        20
          Unrelated       0.44      0.43      0.43        42

           accuracy                           0.44       140
          macro avg       0.44      0.45      0.44       140
       weighted avg       0.43      0.44      0.43       140

In [79]:
X_full = model.encode(
    filtered_df_final["Plaintext"].tolist(),
    show_progress_bar=True
)

Batches: 100%|██████████| 396/396 [26:02<00:00,  3.94s/it]

In [ ]:
filtered_df_final["Predicted_Frame_Logistic"] = clf.predict(X_full)

C:\Users\viggo\AppData\Local\Temp\ipykernel_12656\3998260750.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [81]:
probs = clf.predict_proba(X_full)
print(probs[0])

[0.22372409 0.35222835 0.07804983 0.34599772]

In [ ]:
import plotly.express as px

frame_counts = (
    filtered_df_final["Predicted_Frame_Logistic"]
    .value_counts()
    .reset_index()
)

frame_counts.columns = ["Frame", "Count"]

fig = px.bar(
    frame_counts,
    x="Frame",
    y="Count",
    title="Distribution of Predicted Climate Frames"
)

fig.show()

In [ ]:
channel_frames = (
    filtered_df_final.groupby(
        ["Channel Name", "Predicted_Frame_Logistic"]
    )
    .size()
    .reset_index(name="Count")
)

fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Count",
    color="Predicted_Frame_Logistic",
    title="Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [ ]:
channel_frames = (
    filtered_df_final.groupby(
        ["Channel Name", "Predicted_Frame_Logistic"]
    )
    .size()
    .reset_index(name="Count")
)

# Deleting Unrelated from the Count to only plot Policy, Economy and Science/Expertise
channel_frames = channel_frames[channel_frames["Predicted_Frame_Logistic"] != "Unrelated"]
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Count",
    color="Predicted_Frame_Logistic",
    title="Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [1]:
# Percentage of each frame within each channel
channel_totals = (
    filtered_df_final.groupby("Channel Name")
    .size()
    .reset_index(name="Total")
)
channel_frames = channel_frames.merge(channel_totals, on="Channel Name")
channel_frames["Percentage"] = (channel_frames["Count"] / channel_frames["Total"]) * 100

# Creating a percentage-based bar chart
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Percentage",
    color="Predicted_Frame_Logistic",
    title="Percentage Distribution of Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()
fig.write_html("Charts/Framing_Chart.html")

NameError: name 'filtered_df_final' is not defined

In [ ]:
channel_frames_program = (
    filtered_df_final.groupby(
        ["Channel Program", "Predicted_Frame_Logistic"]
    )
    .size()
    .reset_index(name="Count")
)

# Deleting Unrelated from the Count to only plot Policy, Economy and Science/Expertise
channel_frames_program = channel_frames_program[channel_frames_program["Predicted_Frame_Logistic"] != "Unrelated"]

fig = px.bar(
    channel_frames_program,
    x="Channel Program",
    y="Count",
    color="Predicted_Frame_Logistic",
    title="Predicted Climate Frames by Channel Program",
    barmode="group"
)

fig.show()

### XGBoost

In [90]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.1.3)
Requirement already satisfied: numpy in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\viggo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from xgboost) (1.13.1)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\viggo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [91]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_encoded = le.fit_transform(y)

In [93]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [94]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    objective="multi:softprob",
    num_class=len(le.classes_),

    n_estimators=200,
    max_depth=4,

    learning_rate=0.05,

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None, num_class=4,
              num_parallel_tree=None, ...)

In [95]:
from sklearn.metrics import classification_report

preds = xgb_model.predict(X_test)

print(
    classification_report(
        y_test,
        preds,
        target_names=le.classes_
    )
)

                     precision    recall  f1-score   support

            Economy       0.45      0.54      0.49        39
             Policy       0.41      0.33      0.37        39
Science / Expertise       0.50      0.25      0.33        20
          Unrelated       0.39      0.48      0.43        42

           accuracy                           0.42       140
          macro avg       0.44      0.40      0.40       140
       weighted avg       0.43      0.42      0.41       140

In [97]:
import plotly.express as px
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, preds)

fig = px.imshow(
    cm,
    x=le.classes_,
    y=le.classes_,
    text_auto=True,
    labels=dict(
        x="Predicted",
        y="Actual"
    ),
    title="XGBoost Confusion Matrix"
)

fig.show()

In [98]:
X_full = model.encode(
    filtered_df_final["Plaintext"].tolist(),
    show_progress_bar=True
)

Batches: 100%|██████████| 396/396 [35:42<00:00,  5.41s/it]

In [ ]:
preds = xgb_model.predict(X_full)

filtered_df_final["Predicted_Frame_XGBoost"] = le.inverse_transform(preds)

C:\Users\viggo\AppData\Local\Temp\ipykernel_12656\183119490.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [101]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    xgb_model,
    X,
    y_encoded,
    cv=5,
    scoring="f1_macro"
)

print(scores)
print(scores.mean())

[0.51193975 0.42772466 0.42694099 0.48136185 0.41866396]
0.45332624088631357

In [ ]:
import plotly.express as px

frame_counts = (
    filtered_df_final["Predicted_Frame_XGBoost"]
    .value_counts()
    .reset_index()
)

frame_counts.columns = ["Frame", "Count"]

fig = px.bar(
    frame_counts,
    x="Frame",
    y="Count",
    title="Distribution of Predicted Climate Frames"
)

fig.show()

In [ ]:
channel_frames = (
    filtered_df_final.groupby(
        ["Channel Name", "Predicted_Frame_XGBoost"]
    )
    .size()
    .reset_index(name="Count")
)

# Deleting Unrelated from the Count to only plot Policy, Economy and Science/Expertise
channel_frames = channel_frames[channel_frames["Predicted_Frame_XGBoost"] != "Unrelated"]
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Count",
    color="Predicted_Frame_XGBoost",
    title="Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [ ]:
# Percentage of each frame within each channel
channel_totals = (
    filtered_df_final.groupby("Channel Name")
    .size()
    .reset_index(name="Total")
)
channel_frames = channel_frames.merge(channel_totals, on="Channel Name")
channel_frames["Percentage"] = (channel_frames["Count"] / channel_frames["Total"]) * 100

# Creating a percentage-based bar chart
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Percentage",
    color="Predicted_Frame_XGBoost",
    title="Percentage Distribution of Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

#### Without Unrelated

In [114]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2")

X = model.encode(excerpts["Plaintext"].tolist(), show_progress_bar=True)

y = excerpts["Frame"]

Batches: 100%|██████████| 16/16 [01:31<00:00,  5.73s/it]

In [115]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_encoded = le.fit_transform(y)

In [117]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [118]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    objective="multi:softprob",
    num_class=len(le.classes_),

    n_estimators=200,
    max_depth=4,

    learning_rate=0.05,

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None, num_class=3,
              num_parallel_tree=None, ...)

In [119]:
from sklearn.metrics import classification_report

preds = xgb_model.predict(X_test)

print(
    classification_report(
        y_test,
        preds,
        target_names=le.classes_
    )
)

                     precision    recall  f1-score   support

            Economy       0.55      0.79      0.65        39
             Policy       0.52      0.44      0.47        39
Science / Expertise       0.78      0.35      0.48        20

           accuracy                           0.56        98
          macro avg       0.62      0.53      0.54        98
       weighted avg       0.58      0.56      0.55        98

### k-Nearest Neighbour

In [116]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [106]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(
    n_neighbors=5,
    metric="cosine"
)

knn.fit(X_train, y_train)

KNeighborsClassifier(metric='cosine')

In [107]:
from sklearn.metrics import classification_report

y_pred_knn = knn.predict(X_test)

print(classification_report(y_test, y_pred_knn))

                     precision    recall  f1-score   support

            Economy       0.41      0.51      0.45        39
             Policy       0.35      0.36      0.35        39
Science / Expertise       0.48      0.55      0.51        20
          Unrelated       0.39      0.26      0.31        42

           accuracy                           0.40       140
          macro avg       0.41      0.42      0.41       140
       weighted avg       0.40      0.40      0.39       140

In [108]:
X_full = model.encode(
    filtered_df_final["Plaintext"].tolist(),
    show_progress_bar=True
)

filtered_df_final["Predicted_Frame_kNN"] = knn.predict(X_full)

Batches: 100%|██████████| 396/396 [28:54<00:00,  4.38s/it]
C:\Users\viggo\AppData\Local\Temp\ipykernel_12656\4067078447.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [110]:
filtered_df_final["Predicted_Frame_kNN"].value_counts()

Predicted_Frame_kNN
Unrelated              4851
Economy                3546
Policy                 3288
Science / Expertise     963
Name: count, dtype: int64

In [111]:
channel_frames = (
    filtered_df_final.groupby(
        ["Channel Name", "Predicted_Frame_kNN"]
    )
    .size()
    .reset_index(name="Count")
)

# Deleting Unrelated from the Count to only plot Policy, Economy and Science/Expertise
channel_frames = channel_frames[channel_frames["Predicted_Frame_kNN"] != "Unrelated"]
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Count",
    color="Predicted_Frame_kNN",
    title="Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [112]:
# Percentage of each frame within each channel
channel_totals = (
    filtered_df_final.groupby("Channel Name")
    .size()
    .reset_index(name="Total")
)
channel_frames = channel_frames.merge(channel_totals, on="Channel Name")
channel_frames["Percentage"] = (channel_frames["Count"] / channel_frames["Total"]) * 100

# Creating a percentage-based bar chart
fig = px.bar(
    channel_frames,
    x="Channel Name",
    y="Percentage",
    color="Predicted_Frame_kNN",
    title="Percentage Distribution of Predicted Climate Frames by Channel",
    barmode="group"
)

fig.show()

In [113]:
channel_frames_program = (
    filtered_df_final.groupby(
        ["Channel Program", "Predicted_Frame_kNN"]
    )
    .size()
    .reset_index(name="Count")
)

# Deleting Unrelated from the Count to only plot Policy, Economy and Science/Expertise
channel_frames_program = channel_frames_program[channel_frames_program["Predicted_Frame_kNN"] != "Unrelated"]

fig = px.bar(
    channel_frames_program,
    x="Channel Program",
    y="Count",
    color="Predicted_Frame_kNN",
    title="Predicted Climate Frames by Channel Program",
    barmode="group"
)

fig.show()

#### Without unrelated

In [120]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(
    n_neighbors=5,
    metric="cosine"
)

knn.fit(X_train, y_train)

KNeighborsClassifier(metric='cosine')

In [121]:
from sklearn.metrics import classification_report

y_pred_knn = knn.predict(X_test)

print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.49      0.64      0.56        39
           1       0.42      0.38      0.40        39
           2       0.73      0.40      0.52        20

    accuracy                           0.49        98
   macro avg       0.54      0.48      0.49        98
weighted avg       0.51      0.49      0.49        98